187 implement rddl claim
planetmint/planetmint-go pull request #298
Opened 2024-01-23 16:10 UTC by LaurentMontBlanc

- add RedeemClaim store
- add RedeemClaim msg server (create, update, confirm)
- add RedeemClaim ante handler
- adjust CheckValidatorDecorator for ante handler
- add e2e test case to suite
- add SendUpdateRedeemClaim to util
- add RedeemClaim queries (get by beneficiary and id / get by liquid tx hash)

2024-01-25 16:28 UTC, eckelj requested changes

2024-01-25 16:28 UTC, eckelj commented on x/dao/genesis.go
> +	}
should be removed (see comment above).

2024-01-25 16:28 UTC, eckelj commented on x/dao/genesis.go
> +	genesis.RedeemClaimList = k.GetAllRedeemClaim(ctx)
should be removed (see comment above)

2024-01-25 16:28 UTC, eckelj commented on x/dao/genesis_test.go
> +		RedeemClaimList: []types.RedeemClaim{
should be removed (see comment above)

2024-01-25 16:28 UTC, eckelj commented on x/dao/genesis_test.go
> +	require.ElementsMatch(t, genesisState.RedeemClaimList, got.RedeemClaimList)
should be removed (see comment above)

2024-01-25 16:28 UTC, eckelj commented on x/dao/types/genesis.go
> +		RedeemClaimList: []RedeemClaim{},
to be removed. see above

2024-01-25 16:28 UTC, eckelj commented on x/dao/types/genesis.go
> +	}
to be removed, see above

2024-01-31 19:04 UTC, LaurentMontBlanc commented on proto/planetmintgo/dao/genesis.proto
> +  repeated RedeemClaim redeemClaimList = 2 [(gogoproto.nullable) = false];
done

2024-01-31 19:04 UTC, LaurentMontBlanc commented on x/dao/genesis.go
> +	}
done

2024-01-31 19:04 UTC, LaurentMontBlanc commented on x/dao/genesis_test.go
> +		RedeemClaimList: []types.RedeemClaim{
done

2024-01-31 19:04 UTC, LaurentMontBlanc commented on x/dao/genesis.go
> +	genesis.RedeemClaimList = k.GetAllRedeemClaim(ctx)
done

2024-01-31 19:05 UTC, LaurentMontBlanc commented on x/dao/types/genesis.go
> +		RedeemClaimList: []RedeemClaim{},
done

2024-01-31 19:05 UTC, LaurentMontBlanc commented on x/dao/types/genesis.go
> +	}
done

2024-02-01 08:47 UTC, eckelj approved these changes

2024-02-01 08:57 UTC, merged